package com.cheemcheem.experimental.rubikscubesolver.model;

public enum Move {
  X_LEFT_UP,
  X_LEFT_DOWN,
  X_MIDDLE_UP,
  X_MIDDLE_DOWN,
  X_RIGHT_UP,
  X_RIGHT_DOWN,
  Y_TOP_RIGHT,
  Y_TOP_LEFT,
  Y_MIDDLE_RIGHT,
  Y_MIDDLE_LEFT,
  Y_BOTTOM_RIGHT,
  Y_BOTTOM_LEFT,
  Z_NEAR_CLOCKWISE,
  Z_NEAR_ANTICLOCKWISE,
  Z_MIDDLE_CLOCKWISE,
  Z_MIDDLE_ANTICLOCKWISE,
  Z_FAR_CLOCKWISE,
  Z_FAR_ANTICLOCKWISE;
}
